-- ========================================================
-- 7_visitor_logs.sql
-- 访客 IP 记录与历史数据保留管理
-- ========================================================

create table if not exists visitor_logs (
  id bigint generated by default as identity primary key,
  time timestamptz not null default now(),
  ip text not null default '',
  country text not null default '',
  city text not null default '',
  path text not null default '',
  user_agent text not null default ''
);

create index if not exists idx_visitor_logs_time on visitor_logs(time desc);
create index if not exists idx_visitor_logs_ip on visitor_logs(ip);

alter table visitor_logs enable row level security;
revoke all on visitor_logs from public, anon, authenticated;
grant all on visitor_logs to service_role;

-- 插入访客记录
create or replace function public.cfm_insert_visitor_log(
  input_ip text,
  input_country text default '',
  input_city text default '',
  input_path text default '',
  input_user_agent text default ''
)
returns void
language plpgsql
set search_path = public
as $$
begin
  insert into visitor_logs (ip, country, city, path, user_agent, time)
  values (
    coalesce(nullif(trim(input_ip), ''), 'unknown'),
    coalesce(nullif(trim(input_country), ''), ''),
    coalesce(nullif(trim(input_city), ''), ''),
    coalesce(nullif(trim(input_path), ''), ''),
    coalesce(nullif(trim(input_user_agent), ''), ''),
    now()
  );
end;
$$;

revoke all on function public.cfm_insert_visitor_log(text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.cfm_insert_visitor_log(text, text, text, text, text) to service_role;

-- 分页查询访客记录（支持关键字全局检索与今日访客总数统计）
drop function if exists public.cfm_visitor_logs_paged(integer, integer);

create or replace function public.cfm_visitor_logs_paged(
  input_page integer default 1,
  input_limit integer default 50,
  input_search text default ''
)
returns jsonb
language plpgsql
stable
set search_path = public
as $$
declare
  page_limit integer := least(greatest(coalesce(input_limit, 50), 1), 100);
  page_offset integer := greatest(coalesce(input_page, 1) - 1, 0) * page_limit;
  clean_search text := trim(coalesce(input_search, ''));
  total_count integer;
  today_count integer;
  items jsonb;
  today_start timestamptz := date_trunc('day', now() at time zone 'Asia/Shanghai') at time zone 'Asia/Shanghai';
begin
  -- 统计今日访客总数（基于东八区今日）
  select count(*)::integer into today_count
  from visitor_logs
  where time >= today_start;

  if clean_search <> '' then
    select count(*)::integer into total_count
    from visitor_logs
    where ip ilike '%' || clean_search || '%'
       or country ilike '%' || clean_search || '%'
       or city ilike '%' || clean_search || '%'
       or path ilike '%' || clean_search || '%'
       or user_agent ilike '%' || clean_search || '%';

    select coalesce(jsonb_agg(to_jsonb(r)), '[]'::jsonb) into items
    from (
      select id, time, ip, country, city, path, user_agent
      from visitor_logs
      where ip ilike '%' || clean_search || '%'
         or country ilike '%' || clean_search || '%'
         or city ilike '%' || clean_search || '%'
         or path ilike '%' || clean_search || '%'
         or user_agent ilike '%' || clean_search || '%'
      order by time desc, id desc
      limit page_limit offset page_offset
    ) r;
  else
    select count(*)::integer into total_count from visitor_logs;

    select coalesce(jsonb_agg(to_jsonb(r)), '[]'::jsonb) into items
    from (
      select id, time, ip, country, city, path, user_agent
      from visitor_logs
      order by time desc, id desc
      limit page_limit offset page_offset
    ) r;
  end if;

  return jsonb_build_object(
    'items', items,
    'total', total_count,
    'today_total', today_count
  );
end;
$$;

revoke all on function public.cfm_visitor_logs_paged(integer, integer, text) from public, anon, authenticated;
grant execute on function public.cfm_visitor_logs_paged(integer, integer, text) to service_role;

-- 批次平滑清理过期访客记录（防止大事务锁表与 WAL 膨胀）
create or replace function public.cfm_delete_old_visitor_logs(
  input_before_time text,
  input_max_batches integer default 100
)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  delete_limit integer := least(greatest(coalesce(input_max_batches, 100), 1), 500) * 100;
  deleted_count integer;
begin
  with doomed as (
    select id from visitor_logs
    where time < input_before_time::timestamptz
    order by time, id
    limit delete_limit
  ), deleted as (
    delete from visitor_logs where id in (select id from doomed) returning 1
  )
  select count(*)::integer into deleted_count from deleted;

  return jsonb_build_object('visitor_logs', deleted_count);
end;
$$;

revoke all on function public.cfm_delete_old_visitor_logs(text, integer) from public, anon, authenticated;
grant execute on function public.cfm_delete_old_visitor_logs(text, integer) to service_role;
