-- ========================================================
-- 7_visitor_logs.sql
-- 访客 IP 记录与历史数据保留管理
-- ========================================================

create table if not exists visitor_logs (
  id bigint generated by default as identity primary key,
  time timestamptz not null default now(),
  ip text not null default '',
  country text not null default '',
  city text not null default '',
  path text not null default '',
  user_agent text not null default ''
);

create index if not exists idx_visitor_logs_time on visitor_logs(time desc);
create index if not exists idx_visitor_logs_ip on visitor_logs(ip);

alter table visitor_logs enable row level security;
revoke all on visitor_logs from public, anon, authenticated;
grant all on visitor_logs to service_role;

-- 插入访客记录
create or replace function public.cfm_insert_visitor_log(
  input_ip text,
  input_country text default '',
  input_city text default '',
  input_path text default '',
  input_user_agent text default ''
)
returns void
language plpgsql
set search_path = public
as $$
begin
  insert into visitor_logs (ip, country, city, path, user_agent, time)
  values (
    coalesce(nullif(trim(input_ip), ''), 'unknown'),
    coalesce(nullif(trim(input_country), ''), ''),
    coalesce(nullif(trim(input_city), ''), ''),
    coalesce(nullif(trim(input_path), ''), ''),
    coalesce(nullif(trim(input_user_agent), ''), ''),
    now()
  );
end;
$$;

revoke all on function public.cfm_insert_visitor_log(text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.cfm_insert_visitor_log(text, text, text, text, text) to service_role;

-- 分页查询访客记录
create or replace function public.cfm_visitor_logs_paged(
  input_page integer default 1,
  input_limit integer default 50
)
returns jsonb
language plpgsql
stable
set search_path = public
as $$
declare
  page_offset integer := greatest(input_page - 1, 0) * least(greatest(input_limit, 1), 100);
  page_limit integer := least(greatest(input_limit, 1), 100);
  total_count integer;
  items jsonb;
begin
  select count(*)::integer into total_count from visitor_logs;
  select coalesce(jsonb_agg(to_jsonb(r)), '[]'::jsonb) into items
  from (
    select id, time, ip, country, city, path, user_agent
    from visitor_logs
    order by time desc, id desc
    limit page_limit offset page_offset
  ) r;
  return jsonb_build_object('items', items, 'total', total_count);
end;
$$;

revoke all on function public.cfm_visitor_logs_paged(integer, integer) from public, anon, authenticated;
grant execute on function public.cfm_visitor_logs_paged(integer, integer) to service_role;

-- 批次平滑清理过期访客记录（防止大事务锁表与 WAL 膨胀）
create or replace function public.cfm_delete_old_visitor_logs(
  input_before_time text,
  input_max_batches integer default 100
)
returns jsonb
language plpgsql
set search_path = public
as $$
declare
  delete_limit integer := least(greatest(coalesce(input_max_batches, 100), 1), 500) * 100;
  deleted_count integer;
begin
  with doomed as (
    select id from visitor_logs
    where time < input_before_time::timestamptz
    order by time, id
    limit delete_limit
  ), deleted as (
    delete from visitor_logs where id in (select id from doomed) returning 1
  )
  select count(*)::integer into deleted_count from deleted;

  return jsonb_build_object('visitor_logs', deleted_count);
end;
$$;

revoke all on function public.cfm_delete_old_visitor_logs(text, integer) from public, anon, authenticated;
grant execute on function public.cfm_delete_old_visitor_logs(text, integer) to service_role;
